AllCops:
  Exclude:
    # Exclude all of the rails / rspec / cucumber generated files
    - 'Gemfile'
    - 'Rakefile'
    - 'app/controllers/application_controller.rb'
    - 'bin/setup'
    - 'config/application.rb'
    - 'config/environments/**'
    - 'config/initializers/**'
    - 'features/support/env.rb'
    - 'lib/tasks/cucumber.rake'
    - 'script/cucumber'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'

Documentation:
  Enabled: false

Style/HashSyntax:
    EnforcedStyle: hash_rockets
